using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace AsciiForge;

internal static class ExportService
{
    public static void Save(string path, EffectSettings s, List<string> frames)
    {
        switch (Path.GetExtension(path).ToLowerInvariant())
        {
            case ".ps1": SavePowerShell(path, s, frames); break;
            case ".html": case ".htm": SaveHtml(path, s, frames); break;
            case ".json": SaveJson(path, s, frames); break;
            case ".cs": SaveCSharp(path, s, frames); break;
            case ".ans": SaveAnsi(path, s, frames); break;
            default: File.WriteAllText(path, frames.FirstOrDefault() ?? "", new UTF8Encoding(false)); break;
        }
    }

    private static string Pack(List<string> frames)
    {
        byte[] raw = Encoding.UTF8.GetBytes(JsonSerializer.Serialize(frames));
        using var output = new MemoryStream();
        using (var gz = new GZipStream(output, CompressionLevel.SmallestSize, true)) gz.Write(raw);
        return Convert.ToBase64String(output.ToArray());
    }

    private static void SavePowerShell(string path, EffectSettings s, List<string> frames)
    {
        var data = s.ColorEnabled ? frames.Select(f => ColorizeAnsi(f, s)).ToList() : frames;
        string payload = Pack(data);
        string ps = $$"""
# Generated by AsciiForge 5 C# GPU Edition
# Effect: {{s.Effect}} / {{s.Preset}}
$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.UTF8Encoding]::new($false)
$payload = @'
{{payload}}
'@
$bytes = [Convert]::FromBase64String(($payload -replace '\s',''))
$ms = [IO.MemoryStream]::new($bytes)
$gz = [IO.Compression.GZipStream]::new($ms,[IO.Compression.CompressionMode]::Decompress)
$sr = [IO.StreamReader]::new($gz,[Text.Encoding]::UTF8)
$frames = ConvertFrom-Json $sr.ReadToEnd()
$sr.Dispose(); $gz.Dispose(); $ms.Dispose()
$old = [Console]::CursorVisible
try {
  [Console]::CursorVisible = $false
  [Console]::Clear()
  $frameMs = 1000.0 / {{s.Fps}}
  $sw = [Diagnostics.Stopwatch]::StartNew()
  for($i=0; $i -lt $frames.Count; $i++) {
    [Console]::SetCursorPosition(0,0)
    [Console]::Write([string]$frames[$i])
    $left = [int]((($i+1)*$frameMs)-$sw.Elapsed.TotalMilliseconds)
    if($left -gt 0) { Start-Sleep -Milliseconds $left }
  }
} finally {
  [Console]::Write("`e[0m")
  [Console]::CursorVisible = $old
}
""";
        File.WriteAllText(path, ps, new UTF8Encoding(true));
    }

    private static void SaveHtml(string path, EffectSettings s, List<string> frames)
    {
        var rich = s.ColorEnabled ? frames.Select(f => ColorizeHtml(f, s)).ToList() : frames.Select(f => System.Net.WebUtility.HtmlEncode(f) ?? string.Empty).ToList();
        string richJson = JsonSerializer.Serialize(rich).Replace("</", "<\\/");
        string plainJson = JsonSerializer.Serialize(frames).Replace("</", "<\\/");
        string html = $$$"""
<!doctype html><html><head><meta charset="utf-8"><title>AsciiForge · {{{System.Net.WebUtility.HtmlEncode(s.Effect)}}}</title>
<style>
html,body{height:100%;margin:0;background:#050505;color:#eee}body{display:grid;place-items:center;overflow:auto}
pre{font:14px/1 "Cascadia Mono",Consolas,monospace;white-space:pre;margin:48px;user-select:text;cursor:text}
#bar{position:fixed;left:12px;bottom:12px;display:flex;gap:6px}button{background:#171717;color:#eee;border:1px solid #444;padding:7px 11px;border-radius:5px}
</style></head><body><pre id="s"></pre><div id="bar"><button id="b">Pause</button><button id="copy">Copy frame</button><button id="sel">Select frame</button></div>
<script>
const rich={{{richJson}}},plain={{{plainJson}}},fps={{{s.Fps}}},screen=document.getElementById('s'),btn=document.getElementById('b');
let play=true,start=performance.now(),off=0,hold=false,current=0;
function pause(){if(play){off=performance.now()-start;play=false;btn.textContent='Play'}}
btn.onclick=()=>{play=!play;btn.textContent=play?'Pause':'Play';if(play)start=performance.now()-off};
screen.addEventListener('pointerdown',()=>hold=true);document.addEventListener('pointerup',()=>setTimeout(()=>hold=false,0));
function selected(){const q=getSelection();return q&&!q.isCollapsed&&(screen.contains(q.anchorNode)||screen.contains(q.focusNode))}
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(plain[current])}catch{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r);document.execCommand('copy');q.removeAllRanges()}};
document.getElementById('sel').onclick=()=>{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r)};
function tick(n){if(play&&!hold&&!selected()){current=Math.floor((n-start)*fps/1000)%rich.length;screen.innerHTML=rich[current]}requestAnimationFrame(tick)}
screen.innerHTML=rich[0];requestAnimationFrame(tick);
</script></body></html>
""";
        File.WriteAllText(path, html, new UTF8Encoding(false));
    }

    private static void SaveJson(string path, EffectSettings s, List<string> frames)
    {
        var obj = new { generator = "AsciiForge 5 C# GPU Edition", config = new { s.Effect, s.Preset, s.Width, s.Height, s.Fps, s.Duration, s.Seed, s.Charset, s.PaletteName, s.PaletteStops, s.ColorEnabled, s.Invert, values = s.V }, frames };
        File.WriteAllText(path, JsonSerializer.Serialize(obj, new JsonSerializerOptions { WriteIndented = true }), new UTF8Encoding(false));
    }

    private static void SaveAnsi(string path, EffectSettings s, List<string> frames)
    {
        var data = s.ColorEnabled ? frames.Select(f => ColorizeAnsi(f, s)) : frames;
        File.WriteAllText(path, "\x1b[2J\x1b[?25l" + string.Join("\x1b[H", data) + "\x1b[0m\x1b[?25h\n", new UTF8Encoding(false));
    }

    private static void SaveCSharp(string path, EffectSettings s, List<string> frames)
    {
        string payload = Pack(s.ColorEnabled ? frames.Select(f => ColorizeAnsi(f, s)).ToList() : frames);
        string cs = $$$"""
using System.IO.Compression;
using System.Text;
using System.Text.Json;
const int FPS={{{s.Fps}}};
const string PAYLOAD="{{{payload}}}";
using var ms=new MemoryStream(Convert.FromBase64String(PAYLOAD));using var gz=new GZipStream(ms,CompressionMode.Decompress);using var sr=new StreamReader(gz,Encoding.UTF8);
var frames=JsonSerializer.Deserialize<string[]>(sr.ReadToEnd())??[];Console.OutputEncoding=new UTF8Encoding(false);Console.CursorVisible=false;Console.Clear();var sw=System.Diagnostics.Stopwatch.StartNew();
try{for(int i=0;i<frames.Length;i++){Console.SetCursorPosition(0,0);Console.Write(frames[i]);int left=(int)(((i+1)*1000.0/FPS)-sw.Elapsed.TotalMilliseconds);if(left>0)Thread.Sleep(left);}}finally{Console.Write("\x1b[0m");Console.CursorVisible=true;}
""";
        File.WriteAllText(path, cs, new UTF8Encoding(false));
    }

    private static string ColorizeAnsi(string frame, EffectSettings s)
    {
        var stops = InterpolatePalette(s.PaletteStops, 24); var runes = s.Charset.EnumerateRunes().ToArray(); var map = new Dictionary<string,int>();
        for(int i=0;i<runes.Length;i++)map[runes[i].ToString()]=i;var sb=new StringBuilder();int last=-1;
        foreach(var r in frame.EnumerateRunes())
        {
            if(r.Value=='\n'){sb.Append("\x1b[0m\n");last=-1;continue;}int ri=map.GetValueOrDefault(r.ToString(),r.Value==' '?0:Math.Max(0,runes.Length*3/4));double v=ri/(double)Math.Max(1,runes.Length-1);int lv=Math.Clamp((int)Math.Round(v*(stops.Count-1)),0,stops.Count-1);
            if(lv!=last){var c=stops[lv];sb.Append($"\x1b[38;2;{c.R};{c.G};{c.B}m");last=lv;}sb.Append(r.ToString());
        }
        sb.Append("\x1b[0m");return sb.ToString();
    }

    private static string ColorizeHtml(string frame, EffectSettings s)
    {
        var stops=InterpolatePalette(s.PaletteStops,16);var runes=s.Charset.EnumerateRunes().ToArray();var map=new Dictionary<string,int>();for(int i=0;i<runes.Length;i++)map[runes[i].ToString()]=i;
        var sb=new StringBuilder();int last=-1;var buf=new StringBuilder();void Flush(){if(buf.Length==0)return;var c=stops[Math.Max(0,last)];sb.Append($"<span style=\"color:#{c.R:x2}{c.G:x2}{c.B:x2}\">{System.Net.WebUtility.HtmlEncode(buf.ToString())}</span>");buf.Clear();}
        foreach(var r in frame.EnumerateRunes()){if(r.Value=='\n'){Flush();sb.Append('\n');last=-1;continue;}int ri=map.GetValueOrDefault(r.ToString(),r.Value==' '?0:Math.Max(0,runes.Length*3/4));int lv=Math.Clamp((int)Math.Round(ri/(double)Math.Max(1,runes.Length-1)*(stops.Count-1)),0,stops.Count-1);if(last<0)last=lv;else if(lv!=last){Flush();last=lv;}buf.Append(r.ToString());}Flush();return sb.ToString();
    }

    private static List<Color> InterpolatePalette(List<string> source,int count)
    {
        var src=source.Count>=2?source.Select(Parse).ToList():new List<Color>{Color.Gray,Color.White};var output=new List<Color>(count);for(int i=0;i<count;i++){double p=i/(double)Math.Max(1,count-1)*(src.Count-1);int a=Math.Min(src.Count-2,(int)Math.Floor(p));double t=p-a;var x=src[a];var y=src[a+1];output.Add(Color.FromArgb((int)Math.Round(x.R+(y.R-x.R)*t),(int)Math.Round(x.G+(y.G-x.G)*t),(int)Math.Round(x.B+(y.B-x.B)*t)));}return output;
    }
    private static Color Parse(string s){try{return ColorTranslator.FromHtml(s);}catch{return Color.White;}}
}
