using System.IO.Compression;
using System.Text;
using System.Text.Json;

namespace AsciiForge;

internal static class ExportService
{
    private const string GeneratorName = "AsciiForge 5.2.0 C# GPU Edition";

    public static void Save(string path, EffectSettings settings, List<string> frames)
    {
        switch (Path.GetExtension(path).ToLowerInvariant())
        {
            case ".ps1":
                SavePowerShell(path, settings, frames);
                break;
            case ".html":
            case ".htm":
                SaveHtml(path, settings, frames);
                break;
            case ".json":
                SaveJson(path, settings, frames);
                break;
            case ".cs":
                SaveCSharp(path, settings, frames);
                break;
            case ".ans":
                SaveAnsi(path, settings, frames);
                break;
            default:
                SaveText(path, frames);
                break;
        }
    }

    private static void SavePowerShell(string path, EffectSettings settings, List<string> frames)
    {
        var data = settings.ColorEnabled
            ? frames.Select(frame => ColorizeAnsi(frame, settings)).ToList()
            : frames;
        string payload = Pack(data);
        string credit = settings.IncludeExportCredit
            ? $"# {OutputAttribution.CreditEnglish}\n"
            : string.Empty;

        string script = $$"""
# Generated by {{GeneratorName}}
# Effect: {{settings.Effect}} / {{settings.Preset}}
{{credit}}$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [Text.UTF8Encoding]::new($false)
$payload = @'
{{payload}}
'@
$bytes = [Convert]::FromBase64String(($payload -replace '\s',''))
$ms = [IO.MemoryStream]::new($bytes)
$gz = [IO.Compression.GZipStream]::new($ms,[IO.Compression.CompressionMode]::Decompress)
$sr = [IO.StreamReader]::new($gz,[Text.Encoding]::UTF8)
$frames = ConvertFrom-Json $sr.ReadToEnd()
$sr.Dispose(); $gz.Dispose(); $ms.Dispose()
$old = [Console]::CursorVisible
try {
  [Console]::CursorVisible = $false
  [Console]::Clear()
  $frameMs = 1000.0 / {{settings.Fps}}
  $sw = [Diagnostics.Stopwatch]::StartNew()
  for($i=0; $i -lt $frames.Count; $i++) {
    [Console]::SetCursorPosition(0,0)
    [Console]::Write([string]$frames[$i])
    $left = [int]((($i+1)*$frameMs)-$sw.Elapsed.TotalMilliseconds)
    if($left -gt 0) { Start-Sleep -Milliseconds $left }
  }
} finally {
  [Console]::Write("`e[0m")
  [Console]::CursorVisible = $old
}
""";

        File.WriteAllText(path, script, new UTF8Encoding(true));
    }

    private static void SaveHtml(string path, EffectSettings settings, List<string> frames)
    {
        var richFrames = settings.ColorEnabled
            ? frames.Select(frame => ColorizeHtml(frame, settings)).ToList()
            : frames.Select(frame => System.Net.WebUtility.HtmlEncode(frame) ?? string.Empty).ToList();

        string richJson = JsonSerializer.Serialize(richFrames).Replace("</", "<\\/");
        string plainJson = JsonSerializer.Serialize(frames).Replace("</", "<\\/");
        string attribution = settings.IncludeExportCredit
            ? $"<!-- {OutputAttribution.CreditEnglish} -->\n<meta name=\"generator\" content=\"{GeneratorName}\">"
            : string.Empty;

        string html = $$$"""
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>AsciiForge · {{{System.Net.WebUtility.HtmlEncode(settings.Effect)}}}</title>
{{{attribution}}}
<style>
html,body{height:100%;margin:0;background:#050505;color:#eee}body{display:grid;place-items:center;overflow:auto}
pre{font:14px/1 "Cascadia Mono",Consolas,monospace;white-space:pre;margin:48px;user-select:text;cursor:text}
#bar{position:fixed;left:12px;bottom:12px;display:flex;gap:6px}button{background:#171717;color:#eee;border:1px solid #444;padding:7px 11px;border-radius:5px}
</style>
</head>
<body>
<pre id="s"></pre>
<div id="bar"><button id="b">Pause</button><button id="copy">Copy frame</button><button id="sel">Select frame</button></div>
<script>
const rich={{{richJson}}},plain={{{plainJson}}},fps={{{settings.Fps}}},screen=document.getElementById('s'),btn=document.getElementById('b');
let play=true,start=performance.now(),off=0,hold=false,current=0;
function pause(){if(play){off=performance.now()-start;play=false;btn.textContent='Play'}}
btn.onclick=()=>{play=!play;btn.textContent=play?'Pause':'Play';if(play)start=performance.now()-off};
screen.addEventListener('pointerdown',()=>hold=true);document.addEventListener('pointerup',()=>setTimeout(()=>hold=false,0));
function selected(){const q=getSelection();return q&&!q.isCollapsed&&(screen.contains(q.anchorNode)||screen.contains(q.focusNode))}
document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(plain[current])}catch{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r);document.execCommand('copy');q.removeAllRanges()}};
document.getElementById('sel').onclick=()=>{pause();const r=document.createRange();r.selectNodeContents(screen);const q=getSelection();q.removeAllRanges();q.addRange(r)};
function tick(n){if(play&&!hold&&!selected()){current=Math.floor((n-start)*fps/1000)%rich.length;screen.innerHTML=rich[current]}requestAnimationFrame(tick)}
screen.innerHTML=rich[0];requestAnimationFrame(tick);
</script>
</body>
</html>
""";

        File.WriteAllText(path, html, new UTF8Encoding(false));
    }

    private static void SaveJson(string path, EffectSettings settings, List<string> frames)
    {
        var output = new
        {
            generator = GeneratorName,
            project = settings.IncludeExportCredit ? OutputAttribution.ProjectUrl : null,
            attributionRequested = settings.IncludeExportCredit,
            suggestedCredit = settings.IncludeExportCredit ? OutputAttribution.CreditEnglish : null,
            config = new
            {
                settings.Effect,
                settings.Preset,
                settings.Width,
                settings.Height,
                settings.Fps,
                settings.Duration,
                settings.Seed,
                settings.Charset,
                settings.PaletteName,
                settings.PaletteStops,
                settings.ColorEnabled,
                settings.Invert,
                values = settings.V
            },
            frames
        };

        File.WriteAllText(
            path,
            JsonSerializer.Serialize(output, new JsonSerializerOptions { WriteIndented = true }),
            new UTF8Encoding(false));
    }

    private static void SaveAnsi(string path, EffectSettings settings, List<string> frames)
    {
        var data = settings.ColorEnabled ? frames.Select(frame => ColorizeAnsi(frame, settings)) : frames;
        File.WriteAllText(
            path,
            "\x1b[2J\x1b[?25l" + string.Join("\x1b[H", data) + "\x1b[0m\x1b[?25h\n",
            new UTF8Encoding(false));
    }

    private static void SaveCSharp(string path, EffectSettings settings, List<string> frames)
    {
        string payload = Pack(settings.ColorEnabled
            ? frames.Select(frame => ColorizeAnsi(frame, settings)).ToList()
            : frames);
        string credit = settings.IncludeExportCredit
            ? $"// {OutputAttribution.CreditEnglish}\n"
            : string.Empty;

        string code = $$$"""
// Generated by {{{GeneratorName}}}
{{{credit}}}using System.IO.Compression;
using System.Text;
using System.Text.Json;

const int FPS={{{settings.Fps}}};
const string PAYLOAD="{{{payload}}}";
using var ms=new MemoryStream(Convert.FromBase64String(PAYLOAD));
using var gz=new GZipStream(ms,CompressionMode.Decompress);
using var sr=new StreamReader(gz,Encoding.UTF8);
var frames=JsonSerializer.Deserialize<string[]>(sr.ReadToEnd())??[];
Console.OutputEncoding=new UTF8Encoding(false);
Console.CursorVisible=false;
Console.Clear();
var sw=System.Diagnostics.Stopwatch.StartNew();
try
{
    for(int i=0;i<frames.Length;i++)
    {
        Console.SetCursorPosition(0,0);
        Console.Write(frames[i]);
        int left=(int)(((i+1)*1000.0/FPS)-sw.Elapsed.TotalMilliseconds);
        if(left>0) Thread.Sleep(left);
    }
}
finally
{
    Console.Write("\x1b[0m");
    Console.CursorVisible=true;
}
""";

        File.WriteAllText(path, code, new UTF8Encoding(false));
    }

    private static void SaveText(string path, List<string> frames)
    {
        // Raw text/ANSI formats intentionally stay untouched: adding attribution text
        // would alter the actual ASCII artwork. Attribution is requested in the project notice.
        File.WriteAllText(path, frames.FirstOrDefault() ?? string.Empty, new UTF8Encoding(false));
    }

    private static string Pack(List<string> frames)
    {
        byte[] raw = Encoding.UTF8.GetBytes(JsonSerializer.Serialize(frames));
        using var output = new MemoryStream();
        using (var gz = new GZipStream(output, CompressionLevel.SmallestSize, true))
            gz.Write(raw);
        return Convert.ToBase64String(output.ToArray());
    }

    private static string ColorizeAnsi(string frame, EffectSettings settings)
    {
        var stops = InterpolatePalette(settings.PaletteStops, 24);
        var runes = settings.Charset.EnumerateRunes().ToArray();
        var map = new Dictionary<string, int>();
        for (int i = 0; i < runes.Length; i++) map[runes[i].ToString()] = i;

        var sb = new StringBuilder();
        int last = -1;
        foreach (var rune in frame.EnumerateRunes())
        {
            if (rune.Value == '\n')
            {
                sb.Append("\x1b[0m\n");
                last = -1;
                continue;
            }

            int runeIndex = map.GetValueOrDefault(
                rune.ToString(),
                rune.Value == ' ' ? 0 : Math.Max(0, runes.Length * 3 / 4));
            double value = runeIndex / (double)Math.Max(1, runes.Length - 1);
            int level = Math.Clamp((int)Math.Round(value * (stops.Count - 1)), 0, stops.Count - 1);

            if (level != last)
            {
                var color = stops[level];
                sb.Append($"\x1b[38;2;{color.R};{color.G};{color.B}m");
                last = level;
            }
            sb.Append(rune.ToString());
        }

        sb.Append("\x1b[0m");
        return sb.ToString();
    }

    private static string ColorizeHtml(string frame, EffectSettings settings)
    {
        var stops = InterpolatePalette(settings.PaletteStops, 16);
        var runes = settings.Charset.EnumerateRunes().ToArray();
        var map = new Dictionary<string, int>();
        for (int i = 0; i < runes.Length; i++) map[runes[i].ToString()] = i;

        var sb = new StringBuilder();
        var buffer = new StringBuilder();
        int last = -1;

        void Flush()
        {
            if (buffer.Length == 0) return;
            var color = stops[Math.Max(0, last)];
            sb.Append($"<span style=\"color:#{color.R:x2}{color.G:x2}{color.B:x2}\">{System.Net.WebUtility.HtmlEncode(buffer.ToString())}</span>");
            buffer.Clear();
        }

        foreach (var rune in frame.EnumerateRunes())
        {
            if (rune.Value == '\n')
            {
                Flush();
                sb.Append('\n');
                last = -1;
                continue;
            }

            int runeIndex = map.GetValueOrDefault(
                rune.ToString(),
                rune.Value == ' ' ? 0 : Math.Max(0, runes.Length * 3 / 4));
            int level = Math.Clamp(
                (int)Math.Round(runeIndex / (double)Math.Max(1, runes.Length - 1) * (stops.Count - 1)),
                0,
                stops.Count - 1);

            if (last < 0) last = level;
            else if (level != last)
            {
                Flush();
                last = level;
            }
            buffer.Append(rune.ToString());
        }

        Flush();
        return sb.ToString();
    }

    private static List<Color> InterpolatePalette(List<string> source, int count)
    {
        var input = source.Count >= 2
            ? source.Select(ParseColor).ToList()
            : new List<Color> { Color.Gray, Color.White };
        var output = new List<Color>(count);

        for (int i = 0; i < count; i++)
        {
            double position = i / (double)Math.Max(1, count - 1) * (input.Count - 1);
            int a = Math.Min(input.Count - 2, (int)Math.Floor(position));
            double t = position - a;
            var x = input[a];
            var y = input[a + 1];
            output.Add(Color.FromArgb(
                (int)Math.Round(x.R + (y.R - x.R) * t),
                (int)Math.Round(x.G + (y.G - x.G) * t),
                (int)Math.Round(x.B + (y.B - x.B) * t)));
        }

        return output;
    }

    private static Color ParseColor(string value)
    {
        try { return ColorTranslator.FromHtml(value); }
        catch { return Color.White; }
    }
}
